table desempenho_eleitor_secao_2022_PE
	lineageTag: 4462377d-7ea4-4fd2-8f52-d0864721b2de

	column DS_CARGO
		dataType: string
		lineageTag: ad3e88ff-b5f9-4b1c-84ef-e0016a15c078
		summarizeBy: none
		sourceColumn: DS_CARGO

		annotation SummarizationSetBy = Automatic

	column NR_VOTAVEL
		dataType: int64
		formatString: 0
		lineageTag: ea04302b-7bca-49a1-ad30-77bcc607bd7b
		summarizeBy: sum
		sourceColumn: NR_VOTAVEL

		annotation SummarizationSetBy = Automatic

	column NM_VOTAVEL
		dataType: string
		lineageTag: 79cb68dd-2b1b-46b7-b24c-0c0623d8e55e
		summarizeBy: none
		sourceColumn: NM_VOTAVEL

		annotation SummarizationSetBy = Automatic

	column QT_VOTOS
		dataType: int64
		formatString: 0
		lineageTag: 8409d613-be53-4039-9cc0-607cfbf96ebb
		summarizeBy: sum
		sourceColumn: QT_VOTOS

		annotation SummarizationSetBy = Automatic

	column LOC_KEY
		dataType: string
		lineageTag: d00379f8-440e-4d38-8d82-e5145af5429c
		summarizeBy: none
		sourceColumn: LOC_KEY

		annotation SummarizationSetBy = Automatic

	column COLOCACAO
		dataType: int64
		formatString: 0
		lineageTag: c2fc65b6-c654-47de-90b7-773b74bc14ed
		summarizeBy: sum
		sourceColumn: COLOCACAO

		annotation SummarizationSetBy = Automatic

	column QT_COMPARECIMENTO
		dataType: int64
		formatString: 0
		lineageTag: 59aca9a1-9e3c-48ff-8ebf-15ce3474e718
		summarizeBy: sum
		sourceColumn: QT_COMPARECIMENTO

		annotation SummarizationSetBy = Automatic

	column FEMININO
		dataType: double
		lineageTag: 24d3c9f2-66dd-4f2c-9898-7fe53387d00e
		summarizeBy: sum
		sourceColumn: FEMININO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MASCULINO
		dataType: double
		lineageTag: 6cce293d-02d8-433d-a398-296fcaeada0e
		summarizeBy: sum
		sourceColumn: MASCULINO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ANALFABETO
		dataType: double
		lineageTag: 1c73d7c6-07f9-4f73-98d2-a88013abed7c
		summarizeBy: sum
		sourceColumn: ANALFABETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENSINO_FUNDAMENTAL_COMPLETO
		dataType: double
		lineageTag: 56dc78d9-0b31-45a4-abce-666cbc6d1908
		summarizeBy: sum
		sourceColumn: ENSINO_FUNDAMENTAL_COMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENSINO_FUNDAMENTAL_INCOMPLETO
		dataType: double
		lineageTag: cfb39260-f190-4e8d-aa53-320735cb3720
		summarizeBy: sum
		sourceColumn: ENSINO_FUNDAMENTAL_INCOMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENSINO_MEDIO_COMPLETO
		dataType: double
		lineageTag: b760b23e-161d-4686-a7b7-2ca70830076c
		summarizeBy: sum
		sourceColumn: ENSINO_MEDIO_COMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENSINO_MEDIO_INCOMPLETO
		dataType: double
		lineageTag: bbcab7d4-7682-4938-a83f-23ec8f41e127
		summarizeBy: sum
		sourceColumn: ENSINO_MEDIO_INCOMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LE_E_ESCREVE
		dataType: double
		lineageTag: 2b535f88-03a0-4a4f-9726-1a37057aff31
		summarizeBy: sum
		sourceColumn: LE_E_ESCREVE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SUPERIOR_COMPLETO
		dataType: double
		lineageTag: edb062b2-c28c-4764-ace8-4a56cfae5646
		summarizeBy: sum
		sourceColumn: SUPERIOR_COMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SUPERIOR_INCOMPLETO
		dataType: double
		lineageTag: 0d1f234d-2bae-4e5a-9d7f-308912df14f7
		summarizeBy: sum
		sourceColumn: SUPERIOR_INCOMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 100_ANOS_OU_MAIS
		dataType: int64
		formatString: 0
		lineageTag: d827e44e-08db-4241-a238-205c8c497c4b
		summarizeBy: sum
		sourceColumn: 100_ANOS_OU_MAIS

		annotation SummarizationSetBy = Automatic

	column 16_ANOS
		dataType: double
		lineageTag: 4e4c615c-9a0d-4e19-84bf-7274ff0da6bf
		summarizeBy: sum
		sourceColumn: 16_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 17_ANOS
		dataType: double
		lineageTag: d2ebebcb-7661-4523-af10-c1b9eea98f32
		summarizeBy: sum
		sourceColumn: 17_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 18_ANOS
		dataType: double
		lineageTag: d5f36f3c-1cad-44d9-8632-36906af52b86
		summarizeBy: sum
		sourceColumn: 18_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 19_ANOS
		dataType: double
		lineageTag: 2cd7aaff-4650-4b35-9313-6bfb71488d56
		summarizeBy: sum
		sourceColumn: 19_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 20_ANOS
		dataType: double
		lineageTag: 7e10df5b-d6b2-4067-937b-834c421d6f62
		summarizeBy: sum
		sourceColumn: 20_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 21_A_24_ANOS
		dataType: double
		lineageTag: b30a61cf-b8f4-49c2-9693-0e27c5fc1a67
		summarizeBy: sum
		sourceColumn: 21_A_24_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 25_A_29_ANOS
		dataType: double
		lineageTag: 6beac9b6-ae6b-45c1-9bd2-1d2c48ffcca2
		summarizeBy: sum
		sourceColumn: 25_A_29_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 30_A_34_ANOS
		dataType: double
		lineageTag: 2ba2c12f-3215-46e1-beba-8aa6718a2696
		summarizeBy: sum
		sourceColumn: 30_A_34_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 35_A_39_ANOS
		dataType: double
		lineageTag: 9ae13614-cace-46f3-9049-d5333bc604e3
		summarizeBy: sum
		sourceColumn: 35_A_39_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 40_A_44_ANOS
		dataType: double
		lineageTag: 4261413e-3f15-4348-be88-4963228a8983
		summarizeBy: sum
		sourceColumn: 40_A_44_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 45_A_49_ANOS
		dataType: double
		lineageTag: da64f294-eddc-4bb9-bbfd-d6342eced2a7
		summarizeBy: sum
		sourceColumn: 45_A_49_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 50_A_54_ANOS
		dataType: double
		lineageTag: d66ba431-b699-4709-b431-0ff4e4cc9189
		summarizeBy: sum
		sourceColumn: 50_A_54_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 55_A_59_ANOS
		dataType: double
		lineageTag: e4ed445b-a9d1-4428-89bd-44034a7f2e7e
		summarizeBy: sum
		sourceColumn: 55_A_59_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 60_A_64_ANOS
		dataType: double
		lineageTag: b2848cd3-aeb2-4b9c-bf47-fde97e0b036b
		summarizeBy: sum
		sourceColumn: 60_A_64_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 65_A_69_ANOS
		dataType: double
		lineageTag: 5886120c-967b-4322-9e0d-02dbea6dd0f5
		summarizeBy: sum
		sourceColumn: 65_A_69_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 70_A_74_ANOS
		dataType: double
		lineageTag: c0536de5-d153-4e14-b5a2-8aee7f3d124e
		summarizeBy: sum
		sourceColumn: 70_A_74_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 75_A_79_ANOS
		dataType: double
		lineageTag: f3881469-33a9-459e-bbe6-2ac0f3dc4986
		summarizeBy: sum
		sourceColumn: 75_A_79_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 80_A_84_ANOS
		dataType: double
		lineageTag: 88237e0d-0d32-4cfb-9470-0437f39612bd
		summarizeBy: sum
		sourceColumn: 80_A_84_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 85_A_89_ANOS
		dataType: int64
		formatString: 0
		lineageTag: 37ab8006-11ed-41ce-917a-82107b981f22
		summarizeBy: sum
		sourceColumn: 85_A_89_ANOS

		annotation SummarizationSetBy = Automatic

	column 90_A_94_ANOS
		dataType: double
		lineageTag: b717a0bd-942b-4c5b-9c4a-cf00a14a8c0e
		summarizeBy: sum
		sourceColumn: 90_A_94_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 95_A_99_ANOS
		dataType: int64
		formatString: 0
		lineageTag: a0b12b70-ee8f-4914-9815-8ae4be962e5c
		summarizeBy: sum
		sourceColumn: 95_A_99_ANOS

		annotation SummarizationSetBy = Automatic

	column INVALIDO
		dataType: int64
		formatString: 0
		lineageTag: 4da6bf97-89a4-4b06-bbf3-c39edd1699e2
		summarizeBy: sum
		sourceColumn: INVALIDO

		annotation SummarizationSetBy = Automatic

	column CASADO
		dataType: double
		lineageTag: f031fff6-9178-4e40-97a9-fbeb75047935
		summarizeBy: sum
		sourceColumn: CASADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DIVORCIADO
		dataType: double
		lineageTag: c0d0c32f-42d4-48eb-986b-8ac5ce9a54c5
		summarizeBy: sum
		sourceColumn: DIVORCIADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SEPARADO_JUDICIALMENTE
		dataType: double
		lineageTag: 31c38bf6-4c5c-4519-b656-29a563dedacf
		summarizeBy: sum
		sourceColumn: SEPARADO_JUDICIALMENTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOLTEIRO
		dataType: double
		lineageTag: 3184a2e9-b5ad-44cb-b882-49ffa3fe4f62
		summarizeBy: sum
		sourceColumn: SOLTEIRO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VIUVO
		dataType: double
		lineageTag: 5d82ac36-a2d3-4bab-9383-15dfacb0309c
		summarizeBy: sum
		sourceColumn: VIUVO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TOTAL_ELEITORES
		dataType: int64
		formatString: 0
		lineageTag: c37d4d79-98ea-4678-a84f-2ce8a3bb625c
		summarizeBy: sum
		sourceColumn: TOTAL_ELEITORES

		annotation SummarizationSetBy = Automatic

	partition desempenho_eleitor_secao_2022_PE = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\Pedro\Desktop\CSV_Samples\CENSO_Eleicoes_2022_PE\Parquets\desempenho_secao_2022_PE.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"DS_CARGO", type text}, {"NR_VOTAVEL", Int64.Type}, {"NM_VOTAVEL", type text}, {"QT_VOTOS", Int64.Type}, {"LOC_KEY", type text}, {"COLOCACAO", Int64.Type}, {"QT_COMPARECIMENTO", Int64.Type}, {"FEMININO", type number}, {"MASCULINO", type number}, {"ANALFABETO", type number}, {"ENSINO_FUNDAMENTAL_COMPLETO", type number}, {"ENSINO_FUNDAMENTAL_INCOMPLETO", type number}, {"ENSINO_MEDIO_COMPLETO", type number}, {"ENSINO_MEDIO_INCOMPLETO", type number}, {"LE_E_ESCREVE", type number}, {"SUPERIOR_COMPLETO", type number}, {"SUPERIOR_INCOMPLETO", type number}, {"100_ANOS_OU_MAIS", Int64.Type}, {"16_ANOS", type number}, {"17_ANOS", type number}, {"18_ANOS", type number}, {"19_ANOS", type number}, {"20_ANOS", type number}, {"21_A_24_ANOS", type number}, {"25_A_29_ANOS", type number}, {"30_A_34_ANOS", type number}, {"35_A_39_ANOS", type number}, {"40_A_44_ANOS", type number}, {"45_A_49_ANOS", type number}, {"50_A_54_ANOS", type number}, {"55_A_59_ANOS", type number}, {"60_A_64_ANOS", type number}, {"65_A_69_ANOS", type number}, {"70_A_74_ANOS", type number}, {"75_A_79_ANOS", type number}, {"80_A_84_ANOS", type number}, {"85_A_89_ANOS", Int64.Type}, {"90_A_94_ANOS", type number}, {"95_A_99_ANOS", Int64.Type}, {"INVALIDO", Int64.Type}, {"CASADO", type number}, {"DIVORCIADO", type number}, {"SEPARADO_JUDICIALMENTE", type number}, {"SOLTEIRO", type number}, {"VIUVO", type number}, {"TOTAL_ELEITORES", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

