table perfil_cand_2022_PE
	lineageTag: a6f19ea1-8c11-4fe0-823b-aff867d40d29

	column ANO_ELEICAO
		dataType: int64
		formatString: 0
		lineageTag: 3e08c4c7-7b4a-443c-9d4a-707cedd2150e
		summarizeBy: sum
		sourceColumn: ANO_ELEICAO

		annotation SummarizationSetBy = Automatic

	column SG_UE
		dataType: string
		lineageTag: 8f13dbb5-745f-4160-8412-a622e4423ecd
		summarizeBy: none
		sourceColumn: SG_UE

		annotation SummarizationSetBy = Automatic

	column NM_UE
		dataType: string
		lineageTag: 6368e7ed-e488-41a1-a44e-4d1977ab4127
		summarizeBy: none
		sourceColumn: NM_UE

		annotation SummarizationSetBy = Automatic

	column CD_CARGO
		dataType: int64
		formatString: 0
		lineageTag: 747ee593-aeb1-45e8-84b7-df3b2ec079e0
		summarizeBy: sum
		sourceColumn: CD_CARGO

		annotation SummarizationSetBy = Automatic

	column DS_CARGO
		dataType: string
		lineageTag: c4a3ecef-b1bf-4aff-ba9b-242b33a0e1c5
		summarizeBy: none
		sourceColumn: DS_CARGO

		annotation SummarizationSetBy = Automatic

	column SQ_CANDIDATO
		dataType: int64
		formatString: 0
		lineageTag: 1fb0750c-ea0a-487d-8e87-8bb762667250
		summarizeBy: sum
		sourceColumn: SQ_CANDIDATO

		annotation SummarizationSetBy = Automatic

	column NR_CANDIDATO
		dataType: int64
		formatString: 0
		lineageTag: 6fffb96e-3bf3-43c9-a29e-17eb48aa9f29
		summarizeBy: sum
		sourceColumn: NR_CANDIDATO

		annotation SummarizationSetBy = Automatic

	column NM_CANDIDATO
		dataType: string
		lineageTag: 47801aca-bc2c-4a9a-a99d-cc1085955648
		summarizeBy: none
		sourceColumn: NM_CANDIDATO

		annotation SummarizationSetBy = Automatic

	column NM_URNA_CANDIDATO
		dataType: string
		lineageTag: a0413988-28f6-48ae-bc35-5f4865b2652d
		summarizeBy: none
		sourceColumn: NM_URNA_CANDIDATO

		annotation SummarizationSetBy = Automatic

	column NM_SOCIAL_CANDIDATO
		dataType: string
		lineageTag: 1b8e4579-65de-4cac-bbf2-96f1ee9b80d8
		summarizeBy: none
		sourceColumn: NM_SOCIAL_CANDIDATO

		annotation SummarizationSetBy = Automatic

	column NR_CPF_CANDIDATO
		dataType: int64
		formatString: 0
		lineageTag: b6a08dec-aef4-4779-ac64-221e60c9b655
		summarizeBy: sum
		sourceColumn: NR_CPF_CANDIDATO

		annotation SummarizationSetBy = Automatic

	column CD_SITUACAO_CANDIDATURA
		dataType: int64
		formatString: 0
		lineageTag: 33d7c149-ea87-4862-8995-a7d57992a281
		summarizeBy: sum
		sourceColumn: CD_SITUACAO_CANDIDATURA

		annotation SummarizationSetBy = Automatic

	column DS_SITUACAO_CANDIDATURA
		dataType: string
		lineageTag: 78fa6475-da97-4a14-9358-3b36889d3c17
		summarizeBy: none
		sourceColumn: DS_SITUACAO_CANDIDATURA

		annotation SummarizationSetBy = Automatic

	column TP_AGREMIACAO
		dataType: string
		lineageTag: 5a35669e-80b9-46d1-9b06-6e44ea7b4850
		summarizeBy: none
		sourceColumn: TP_AGREMIACAO

		annotation SummarizationSetBy = Automatic

	column NR_PARTIDO
		dataType: int64
		formatString: 0
		lineageTag: 4338f997-55dd-4b5d-ae54-a570a1996c89
		summarizeBy: sum
		sourceColumn: NR_PARTIDO

		annotation SummarizationSetBy = Automatic

	column SG_PARTIDO
		dataType: string
		lineageTag: 7cb59c4a-c0ac-40e7-9a29-8604ed07a66d
		summarizeBy: none
		sourceColumn: SG_PARTIDO

		annotation SummarizationSetBy = Automatic

	column NM_PARTIDO
		dataType: string
		lineageTag: 6f983af5-1d47-454d-83b5-af4d9aa117a4
		summarizeBy: none
		sourceColumn: NM_PARTIDO

		annotation SummarizationSetBy = Automatic

	column NR_FEDERACAO
		dataType: int64
		formatString: 0
		lineageTag: 68deb318-5aa4-4677-a3f4-7208d71aa87b
		summarizeBy: sum
		sourceColumn: NR_FEDERACAO

		annotation SummarizationSetBy = Automatic

	column NM_FEDERACAO
		dataType: string
		lineageTag: 442fc598-687e-44f8-9c01-a2df8bb376a6
		summarizeBy: none
		sourceColumn: NM_FEDERACAO

		annotation SummarizationSetBy = Automatic

	column SG_FEDERACAO
		dataType: string
		lineageTag: ea7b62b9-0cfa-4788-89a8-33c6013c9a6d
		summarizeBy: none
		sourceColumn: SG_FEDERACAO

		annotation SummarizationSetBy = Automatic

	column DS_COMPOSICAO_FEDERACAO
		dataType: string
		lineageTag: 421962d3-dfa7-4756-8bab-05e9b31a2b17
		summarizeBy: none
		sourceColumn: DS_COMPOSICAO_FEDERACAO

		annotation SummarizationSetBy = Automatic

	column SQ_COLIGACAO
		dataType: int64
		formatString: 0
		lineageTag: b85a2794-eaf0-4b62-816e-e469385617a1
		summarizeBy: sum
		sourceColumn: SQ_COLIGACAO

		annotation SummarizationSetBy = Automatic

	column NM_COLIGACAO
		dataType: string
		lineageTag: dd975dd5-9df3-4b8e-83ed-cdd2756b96ac
		summarizeBy: none
		sourceColumn: NM_COLIGACAO

		annotation SummarizationSetBy = Automatic

	column DS_COMPOSICAO_COLIGACAO
		dataType: string
		lineageTag: 8ee3b932-8ade-408b-9bc1-ef707a8771bc
		summarizeBy: none
		sourceColumn: DS_COMPOSICAO_COLIGACAO

		annotation SummarizationSetBy = Automatic

	column SG_UF_NASCIMENTO
		dataType: string
		lineageTag: ad3d9e5a-efcb-4359-86d5-4cd34ef2d0c8
		summarizeBy: none
		sourceColumn: SG_UF_NASCIMENTO

		annotation SummarizationSetBy = Automatic

	column DT_NASCIMENTO
		dataType: dateTime
		formatString: Long Date
		lineageTag: f5d2e4eb-0461-4859-a3d0-034379040fc7
		summarizeBy: none
		sourceColumn: DT_NASCIMENTO

		variation Variation
			isDefault
			relationship: 76a582c9-97d6-4e6d-ac09-8be4162ef6f1
			defaultHierarchy: LocalDateTable_ed1afeae-2361-4e43-b1b8-d3708d7df811.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NR_TITULO_ELEITORAL_CANDIDATO
		dataType: int64
		formatString: 0
		lineageTag: 53062bea-6b0d-496e-8b03-dcadc3a9a498
		summarizeBy: sum
		sourceColumn: NR_TITULO_ELEITORAL_CANDIDATO

		annotation SummarizationSetBy = Automatic

	column CD_GENERO
		dataType: int64
		formatString: 0
		lineageTag: e3ee5843-ec99-4d23-a524-f7558e53ac47
		summarizeBy: sum
		sourceColumn: CD_GENERO

		annotation SummarizationSetBy = Automatic

	column DS_GENERO
		dataType: string
		lineageTag: bd9371fe-5a25-4bf9-95d2-b1e8a5dca81f
		summarizeBy: none
		sourceColumn: DS_GENERO

		annotation SummarizationSetBy = Automatic

	column CD_GRAU_INSTRUCAO
		dataType: int64
		formatString: 0
		lineageTag: 09126679-71d9-4a08-a876-0ff6b7f78166
		summarizeBy: sum
		sourceColumn: CD_GRAU_INSTRUCAO

		annotation SummarizationSetBy = Automatic

	column DS_GRAU_INSTRUCAO
		dataType: string
		lineageTag: 98ae0c76-1c5c-4306-8298-b9d23387bb90
		summarizeBy: none
		sourceColumn: DS_GRAU_INSTRUCAO

		annotation SummarizationSetBy = Automatic

	column CD_ESTADO_CIVIL
		dataType: int64
		formatString: 0
		lineageTag: 7b4afe5f-367b-4617-9425-e8274aca47b0
		summarizeBy: sum
		sourceColumn: CD_ESTADO_CIVIL

		annotation SummarizationSetBy = Automatic

	column DS_ESTADO_CIVIL
		dataType: string
		lineageTag: adf35408-2674-4d32-a640-62dfaec5d432
		summarizeBy: none
		sourceColumn: DS_ESTADO_CIVIL

		annotation SummarizationSetBy = Automatic

	column CD_COR_RACA
		dataType: int64
		formatString: 0
		lineageTag: c5324248-ff99-46d0-b8b1-492e644eb0e5
		summarizeBy: sum
		sourceColumn: CD_COR_RACA

		annotation SummarizationSetBy = Automatic

	column DS_COR_RACA
		dataType: string
		lineageTag: 7305b4fc-dd94-467d-bd43-75fa5123588b
		summarizeBy: none
		sourceColumn: DS_COR_RACA

		annotation SummarizationSetBy = Automatic

	column CD_OCUPACAO
		dataType: int64
		formatString: 0
		lineageTag: 48766f6f-ab43-40c0-91a4-c9bfcca1b7dc
		summarizeBy: sum
		sourceColumn: CD_OCUPACAO

		annotation SummarizationSetBy = Automatic

	column DS_OCUPACAO
		dataType: string
		lineageTag: e0165fe7-06f1-492b-9469-266ba67e7a67
		summarizeBy: none
		sourceColumn: DS_OCUPACAO

		annotation SummarizationSetBy = Automatic

	column CD_SIT_TOT_TURNO
		dataType: int64
		formatString: 0
		lineageTag: f387241e-4bdb-4c75-9424-9f0505107ef5
		summarizeBy: sum
		sourceColumn: CD_SIT_TOT_TURNO

		annotation SummarizationSetBy = Automatic

	column DS_SIT_TOT_TURNO
		dataType: string
		lineageTag: fe190236-271d-4844-9ab2-067376f0aaaf
		summarizeBy: none
		sourceColumn: DS_SIT_TOT_TURNO

		annotation SummarizationSetBy = Automatic

	column CAND_KEY
		dataType: string
		lineageTag: 9c68bb1a-16ef-4c75-9f3c-8702d366ece5
		summarizeBy: none
		sourceColumn: CAND_KEY

		annotation SummarizationSetBy = Automatic

	partition perfil_cand_2022_PE = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("C:\Users\Pedro\Desktop\consulta_cand_2022_PE.csv"),[Delimiter=";", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DT_GERACAO", type date}, {"HH_GERACAO", type time}, {"ANO_ELEICAO", Int64.Type}, {"CD_TIPO_ELEICAO", Int64.Type}, {"NM_TIPO_ELEICAO", type text}, {"NR_TURNO", Int64.Type}, {"CD_ELEICAO", Int64.Type}, {"DS_ELEICAO", type text}, {"DT_ELEICAO", type date}, {"TP_ABRANGENCIA", type text}, {"SG_UF", type text}, {"SG_UE", type text}, {"NM_UE", type text}, {"CD_CARGO", Int64.Type}, {"DS_CARGO", type text}, {"SQ_CANDIDATO", Int64.Type}, {"NR_CANDIDATO", Int64.Type}, {"NM_CANDIDATO", type text}, {"NM_URNA_CANDIDATO", type text}, {"NM_SOCIAL_CANDIDATO", type text}, {"NR_CPF_CANDIDATO", Int64.Type}, {"DS_EMAIL", type text}, {"CD_SITUACAO_CANDIDATURA", Int64.Type}, {"DS_SITUACAO_CANDIDATURA", type text}, {"TP_AGREMIACAO", type text}, {"NR_PARTIDO", Int64.Type}, {"SG_PARTIDO", type text}, {"NM_PARTIDO", type text}, {"NR_FEDERACAO", Int64.Type}, {"NM_FEDERACAO", type text}, {"SG_FEDERACAO", type text}, {"DS_COMPOSICAO_FEDERACAO", type text}, {"SQ_COLIGACAO", Int64.Type}, {"NM_COLIGACAO", type text}, {"DS_COMPOSICAO_COLIGACAO", type text}, {"SG_UF_NASCIMENTO", type text}, {"DT_NASCIMENTO", type date}, {"NR_TITULO_ELEITORAL_CANDIDATO", Int64.Type}, {"CD_GENERO", Int64.Type}, {"DS_GENERO", type text}, {"CD_GRAU_INSTRUCAO", Int64.Type}, {"DS_GRAU_INSTRUCAO", type text}, {"CD_ESTADO_CIVIL", Int64.Type}, {"DS_ESTADO_CIVIL", type text}, {"CD_COR_RACA", Int64.Type}, {"DS_COR_RACA", type text}, {"CD_OCUPACAO", Int64.Type}, {"DS_OCUPACAO", type text}, {"CD_SIT_TOT_TURNO", Int64.Type}, {"DS_SIT_TOT_TURNO", type text}}),
				    #"▼ Tratamento tabela" = #"Changed Type",
				    #"Removed Columns" = Table.RemoveColumns(#"▼ Tratamento tabela",{"DT_GERACAO", "HH_GERACAO", "CD_TIPO_ELEICAO", "NM_TIPO_ELEICAO", "NR_TURNO", "CD_ELEICAO", "DS_ELEICAO", "DT_ELEICAO", "TP_ABRANGENCIA", "SG_UF", "DS_EMAIL"}),
				    #"Added Custom" = Table.AddColumn(
				    #"Removed Columns",
				    "CAND_KEY",
				    each 
				        Text.From([DS_CARGO]) & 
				        "-" & 
				        Text.From([NR_CANDIDATO]),
				    type text
				)
				in
				    #"Added Custom"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

