table perfil_eleitor_secao_2022_PE
	lineageTag: f0b7d84e-f682-4925-a70e-7315ef20a2ca

	column NM_MUNICIPIO
		dataType: string
		lineageTag: bfe16cc9-36bc-47de-90fe-1871a573ae49
		summarizeBy: none
		sourceColumn: NM_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column NR_ZONA
		dataType: int64
		formatString: 0
		lineageTag: 5b412cc2-430f-4d2b-8e2c-5a2ab60026eb
		summarizeBy: sum
		sourceColumn: NR_ZONA

		annotation SummarizationSetBy = Automatic

	column NR_SECAO
		dataType: int64
		formatString: 0
		lineageTag: 5cd999e1-cad5-4bab-8e5e-fa68f0577d9c
		summarizeBy: sum
		sourceColumn: NR_SECAO

		annotation SummarizationSetBy = Automatic

	column DS_GENERO
		dataType: string
		lineageTag: da13f390-1b7e-4a22-88a5-ce42857638c0
		summarizeBy: none
		sourceColumn: DS_GENERO

		annotation SummarizationSetBy = Automatic

	column DS_ESTADO_CIVIL
		dataType: string
		lineageTag: b218c943-46be-4f9e-be18-68591824092b
		summarizeBy: none
		sourceColumn: DS_ESTADO_CIVIL

		annotation SummarizationSetBy = Automatic

	column DS_FAIXA_ETARIA
		dataType: string
		lineageTag: 3ab8ae3a-3db4-433c-a0ed-c8d108385555
		summarizeBy: none
		sourceColumn: DS_FAIXA_ETARIA

		annotation SummarizationSetBy = Automatic

	column DS_GRAU_ESCOLARIDADE
		dataType: string
		lineageTag: 2b53006e-d6c6-4a9c-b072-4aca916bd93f
		summarizeBy: none
		sourceColumn: DS_GRAU_ESCOLARIDADE

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES_PERFIL
		dataType: int64
		formatString: 0
		lineageTag: 2d7a4230-501d-4225-bdf6-e78e7d2a6d68
		summarizeBy: sum
		sourceColumn: QT_ELEITORES_PERFIL

		annotation SummarizationSetBy = Automatic

	column ANO_ELEICAO
		dataType: int64
		formatString: 0
		lineageTag: e621ec37-1365-40e4-898f-f5029969b039
		summarizeBy: sum
		sourceColumn: ANO_ELEICAO

		annotation SummarizationSetBy = Automatic

	column SG_UF
		dataType: string
		lineageTag: fb664db0-973b-40a4-9037-8a4676a34f24
		summarizeBy: none
		sourceColumn: SG_UF

		annotation SummarizationSetBy = Automatic

	column GP_FAIXA_ETARIA
		dataType: string
		lineageTag: 86383679-a998-4077-b66c-658652d66eb5
		summarizeBy: none
		sourceColumn: GP_FAIXA_ETARIA

		annotation SummarizationSetBy = Automatic

	column LOC_KEY
		dataType: string
		lineageTag: bdf3fc14-b4b4-4ed7-8c48-06fcc83b5f75
		summarizeBy: none
		sourceColumn: LOC_KEY

		annotation SummarizationSetBy = Automatic

	column 'Unnamed: 0'
		dataType: int64
		formatString: 0
		lineageTag: 28bf5b92-13d0-49cd-91de-27ff1b07c60f
		summarizeBy: sum
		sourceColumn: Unnamed: 0

		annotation SummarizationSetBy = Automatic

	partition perfil_eleitor_secao_2022_PE = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\Pedro\Desktop\CSV_Samples\CENSO_Eleicoes_2022_PE\Parquets\perfil_eleitor_secao_2022_PE.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Unnamed: 0", Int64.Type}, {"NM_MUNICIPIO", type text}, {"NR_ZONA", Int64.Type}, {"NR_SECAO", Int64.Type}, {"DS_GENERO", type text}, {"DS_ESTADO_CIVIL", type text}, {"DS_FAIXA_ETARIA", type text}, {"DS_GRAU_ESCOLARIDADE", type text}, {"QT_ELEITORES_PERFIL", Int64.Type}, {"LOC_KEY", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

