table presenca_secao_2022_PE
	lineageTag: 5db30a0e-4c05-4b58-8f68-b42046f2882f

	column NM_MUNICIPIO
		dataType: string
		lineageTag: ebe97252-edba-4437-ac6d-a7b3c51e4e15
		dataCategory: City
		summarizeBy: none
		sourceColumn: NM_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column NR_ZONA
		dataType: int64
		formatString: 0
		lineageTag: f64c011a-6725-4621-9e78-1ba098f4201c
		summarizeBy: sum
		sourceColumn: NR_ZONA

		annotation SummarizationSetBy = Automatic

	column NR_SECAO
		dataType: int64
		formatString: 0
		lineageTag: be0f4e65-2cac-4af0-beb2-4180be1f16dc
		summarizeBy: sum
		sourceColumn: NR_SECAO

		annotation SummarizationSetBy = Automatic

	column QT_APTOS
		dataType: int64
		formatString: 0
		lineageTag: e284939d-9c34-423f-bb16-bb1047638022
		summarizeBy: sum
		sourceColumn: QT_APTOS

		annotation SummarizationSetBy = Automatic

	column QT_COMPARECIMENTO
		dataType: int64
		formatString: 0
		lineageTag: 61e18ecd-bd7e-47c9-9e8a-0b43d181a8ed
		summarizeBy: sum
		sourceColumn: QT_COMPARECIMENTO

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: cf95255b-e3b7-4c6b-965e-46c5d658e6e4
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column SG_UF
		dataType: string
		lineageTag: f70e16ed-5ec2-4424-a9a4-e6f4b6cd520a
		summarizeBy: none
		sourceColumn: SG_UF

		annotation SummarizationSetBy = Automatic

	column LOC_KEY
		dataType: string
		lineageTag: d9835ca7-6076-48bf-8e64-a8f8793a8527
		summarizeBy: none
		sourceColumn: LOC_KEY

		annotation SummarizationSetBy = Automatic

	column __index_level_0__
		dataType: int64
		formatString: 0
		lineageTag: 1af7400a-6fea-46e0-be77-44e3efcee595
		summarizeBy: sum
		sourceColumn: __index_level_0__

		annotation SummarizationSetBy = Automatic

	partition presenca_secao_2022_PE = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\Pedro\Desktop\CSV_Samples\CENSO_Eleicoes_2022_PE\Parquets\presenca_votacao_secao_2022_PE.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"NM_MUNICIPIO", type text}, {"NR_ZONA", Int64.Type}, {"NR_SECAO", Int64.Type}, {"QT_APTOS", Int64.Type}, {"QT_COMPARECIMENTO", Int64.Type}, {"LOC_KEY", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"PERC_COMPARECIMENTO", "NR_TURNO", "CD_TIPO_ELEICAO", "DS_ELEICAO"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "UF", each "Pernambuco")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

