table resultados_secao_2022_PE
	lineageTag: a5de3243-3e86-44ca-a5ff-1b1a171b5c20

	column LOC_KEY
		dataType: string
		lineageTag: e090ea6c-c5c8-44e3-a73d-a66c4365a827
		summarizeBy: none
		sourceColumn: LOC_KEY

		annotation SummarizationSetBy = Automatic

	column NM_VOTAVEL
		dataType: string
		lineageTag: 61ae1a46-d5ce-46cd-a28a-8cd047c49971
		summarizeBy: none
		sourceColumn: NM_VOTAVEL

		annotation SummarizationSetBy = Automatic

	column NR_VOTAVEL
		dataType: int64
		formatString: 0
		lineageTag: 5e1827d1-ad38-421e-9cca-366491c52196
		summarizeBy: sum
		sourceColumn: NR_VOTAVEL

		annotation SummarizationSetBy = Automatic

	column COLOCACAO
		dataType: int64
		formatString: 0
		lineageTag: 470f1ae5-79db-4191-9eb0-fb60a6bf4fe8
		summarizeBy: sum
		sourceColumn: COLOCACAO

		annotation SummarizationSetBy = Automatic

	column DIST_MAHALANOBIS
		dataType: double
		lineageTag: 40bf937d-8f3a-4bd7-bc32-622581a1dd2e
		summarizeBy: sum
		sourceColumn: DIST_MAHALANOBIS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_FEMININO
		dataType: double
		lineageTag: fc107aa0-a422-4b0f-b816-82113c7ea69b
		summarizeBy: sum
		sourceColumn: PERFIL_FEMININO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_ANALFABETO
		dataType: double
		lineageTag: aba4a253-13c7-46a8-9d31-0163cca3cd47
		summarizeBy: sum
		sourceColumn: PERFIL_ANALFABETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_ENSINO_FUNDAMENTAL_COMPLETO
		dataType: double
		lineageTag: 500f6f29-cf5d-4158-af93-7abaa1422bd9
		summarizeBy: sum
		sourceColumn: PERFIL_ENSINO_FUNDAMENTAL_COMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_ENSINO_FUNDAMENTAL_INCOMPLETO
		dataType: double
		lineageTag: bb75df34-e748-40cc-a4b4-b7af3cb87965
		summarizeBy: sum
		sourceColumn: PERFIL_ENSINO_FUNDAMENTAL_INCOMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_ENSINO_MEDIO_COMPLETO
		dataType: double
		lineageTag: 3ae62807-67ab-49fd-b3ae-b598dd62ab23
		summarizeBy: sum
		sourceColumn: PERFIL_ENSINO_MEDIO_COMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_ENSINO_MEDIO_INCOMPLETO
		dataType: double
		lineageTag: 65895805-1e91-4ac5-9f26-fddbc61afe67
		summarizeBy: sum
		sourceColumn: PERFIL_ENSINO_MEDIO_INCOMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_SUPERIOR_COMPLETO
		dataType: double
		lineageTag: c3c99021-2140-44cb-946c-79eb97301f56
		summarizeBy: sum
		sourceColumn: PERFIL_SUPERIOR_COMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_SUPERIOR_INCOMPLETO
		dataType: double
		lineageTag: 1b1259da-1643-46cd-94ee-c95d2707c15f
		summarizeBy: sum
		sourceColumn: PERFIL_SUPERIOR_INCOMPLETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_16_ANOS
		dataType: double
		lineageTag: 263355ab-04d9-47ae-abcf-0b2f6221c16a
		summarizeBy: sum
		sourceColumn: PERFIL_16_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_17_ANOS
		dataType: double
		lineageTag: afa3d6b0-6de2-4133-94e5-cc52afcc380f
		summarizeBy: sum
		sourceColumn: PERFIL_17_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_18_ANOS
		dataType: double
		lineageTag: 32c2b1ca-56e9-45b7-b04c-a7c7dfe8239f
		summarizeBy: sum
		sourceColumn: PERFIL_18_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_19_ANOS
		dataType: double
		lineageTag: d4d7f252-6674-496a-b845-1e99def67c23
		summarizeBy: sum
		sourceColumn: PERFIL_19_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_20_ANOS
		dataType: double
		lineageTag: 6f1988dd-e129-45b9-a51b-820dc758b32a
		summarizeBy: sum
		sourceColumn: PERFIL_20_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_21_A_24_ANOS
		dataType: double
		lineageTag: c095b6a7-6b90-4f08-89b2-f5307c919e77
		summarizeBy: sum
		sourceColumn: PERFIL_21_A_24_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_25_A_29_ANOS
		dataType: double
		lineageTag: a4823a4e-093d-42d0-9398-703affc72272
		summarizeBy: sum
		sourceColumn: PERFIL_25_A_29_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_30_A_34_ANOS
		dataType: double
		lineageTag: 447ca2f5-fd12-4317-8d45-b1a859830810
		summarizeBy: sum
		sourceColumn: PERFIL_30_A_34_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_35_A_39_ANOS
		dataType: double
		lineageTag: 929458fb-4562-4567-b715-658ae4c4cbb2
		summarizeBy: sum
		sourceColumn: PERFIL_35_A_39_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_40_A_44_ANOS
		dataType: double
		lineageTag: e84493eb-d513-4818-9fe3-2b63922a1c0b
		summarizeBy: sum
		sourceColumn: PERFIL_40_A_44_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_45_A_49_ANOS
		dataType: double
		lineageTag: 17f37440-d624-40d9-b7ad-99729201c4f1
		summarizeBy: sum
		sourceColumn: PERFIL_45_A_49_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_50_A_54_ANOS
		dataType: double
		lineageTag: ba56feb5-fffc-48a7-9545-3ddf97c3b341
		summarizeBy: sum
		sourceColumn: PERFIL_50_A_54_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_55_A_59_ANOS
		dataType: double
		lineageTag: 10a71c13-373e-400d-b139-77767abd5c34
		summarizeBy: sum
		sourceColumn: PERFIL_55_A_59_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_60_A_64_ANOS
		dataType: double
		lineageTag: b5d77187-e6d3-4402-bf7f-32ea708186fd
		summarizeBy: sum
		sourceColumn: PERFIL_60_A_64_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_65_A_69_ANOS
		dataType: double
		lineageTag: 5ba79fa6-ccc1-43e8-9c40-36a3f0bd01f6
		summarizeBy: sum
		sourceColumn: PERFIL_65_A_69_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_70_A_74_ANOS
		dataType: double
		lineageTag: e1649f67-bd12-4266-9339-c2f8139c9a80
		summarizeBy: sum
		sourceColumn: PERFIL_70_A_74_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_75_A_79_ANOS
		dataType: double
		lineageTag: bf25892f-980a-4a29-923d-c178fe204ee5
		summarizeBy: sum
		sourceColumn: PERFIL_75_A_79_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_80_A_84_ANOS
		dataType: double
		lineageTag: a9df25f9-43d4-4e64-b50f-d006bcc47bad
		summarizeBy: sum
		sourceColumn: PERFIL_80_A_84_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_85_A_89_ANOS
		dataType: double
		lineageTag: fd2e3bf3-e6ee-4c8e-96b3-3aaf748abecf
		summarizeBy: sum
		sourceColumn: PERFIL_85_A_89_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_90_A_94_ANOS
		dataType: double
		lineageTag: a9c28c16-9ddf-4de8-b975-a51562b02f1b
		summarizeBy: sum
		sourceColumn: PERFIL_90_A_94_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_95_A_99_ANOS
		dataType: double
		lineageTag: cbadc053-a902-46a6-aecb-4d8dda68fecc
		summarizeBy: sum
		sourceColumn: PERFIL_95_A_99_ANOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_CASADO
		dataType: double
		lineageTag: f8126151-b4eb-494f-abdb-4f69f7bd1df2
		summarizeBy: sum
		sourceColumn: PERFIL_CASADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_DIVORCIADO
		dataType: double
		lineageTag: 4481dae2-0782-4258-b317-a52b5482b0e0
		summarizeBy: sum
		sourceColumn: PERFIL_DIVORCIADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_SEPARADO_JUDICIALMENTE
		dataType: double
		lineageTag: e8f2f85a-ada9-408f-af02-ba4c20e6834f
		summarizeBy: sum
		sourceColumn: PERFIL_SEPARADO_JUDICIALMENTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERFIL_SOLTEIRO
		dataType: double
		lineageTag: bdc24655-e093-43b2-b86d-f4415ed73cea
		summarizeBy: sum
		sourceColumn: PERFIL_SOLTEIRO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition resultados_secao_2022_PE = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\Pedro\Desktop\CSV_Samples\CENSO_Eleicoes_2022_PE\Parquets\resultados.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"LOC_KEY", type text}, {"NM_VOTAVEL", type text}, {"NR_VOTAVEL", Int64.Type}, {"COLOCACAO", Int64.Type}, {"DIST_MAHALANOBIS", type number}, {"PERFIL_FEMININO", type number}, {"PERFIL_ANALFABETO", type number}, {"PERFIL_ENSINO_FUNDAMENTAL_COMPLETO", type number}, {"PERFIL_ENSINO_FUNDAMENTAL_INCOMPLETO", type number}, {"PERFIL_ENSINO_MEDIO_COMPLETO", type number}, {"PERFIL_ENSINO_MEDIO_INCOMPLETO", type number}, {"PERFIL_SUPERIOR_COMPLETO", type number}, {"PERFIL_SUPERIOR_INCOMPLETO", type number}, {"PERFIL_16_ANOS", type number}, {"PERFIL_17_ANOS", type number}, {"PERFIL_18_ANOS", type number}, {"PERFIL_19_ANOS", type number}, {"PERFIL_20_ANOS", type number}, {"PERFIL_21_A_24_ANOS", type number}, {"PERFIL_25_A_29_ANOS", type number}, {"PERFIL_30_A_34_ANOS", type number}, {"PERFIL_35_A_39_ANOS", type number}, {"PERFIL_40_A_44_ANOS", type number}, {"PERFIL_45_A_49_ANOS", type number}, {"PERFIL_50_A_54_ANOS", type number}, {"PERFIL_55_A_59_ANOS", type number}, {"PERFIL_60_A_64_ANOS", type number}, {"PERFIL_65_A_69_ANOS", type number}, {"PERFIL_70_A_74_ANOS", type number}, {"PERFIL_75_A_79_ANOS", type number}, {"PERFIL_80_A_84_ANOS", type number}, {"PERFIL_85_A_89_ANOS", type number}, {"PERFIL_90_A_94_ANOS", type number}, {"PERFIL_95_A_99_ANOS", type number}, {"PERFIL_CASADO", type number}, {"PERFIL_DIVORCIADO", type number}, {"PERFIL_SEPARADO_JUDICIALMENTE", type number}, {"PERFIL_SOLTEIRO", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

