table votacao_secao_2022_PE
	lineageTag: 20365395-a5df-40b9-ae90-c46923de03ea

	column NR_ZONA
		dataType: int64
		formatString: 0
		lineageTag: eb8288b0-819c-471d-9921-71e7095ae10d
		summarizeBy: sum
		sourceColumn: NR_ZONA

		annotation SummarizationSetBy = Automatic

	column NR_SECAO
		dataType: int64
		formatString: 0
		lineageTag: 937c9dc6-e438-4271-9733-9f0b91dd0702
		summarizeBy: sum
		sourceColumn: NR_SECAO

		annotation SummarizationSetBy = Automatic

	column DS_CARGO
		dataType: string
		lineageTag: ca910062-3c9c-4bc0-b209-636c3ee655e6
		summarizeBy: none
		sourceColumn: DS_CARGO

		annotation SummarizationSetBy = Automatic

	column NR_VOTAVEL
		dataType: int64
		formatString: 0
		lineageTag: d36181fe-1bf3-4eba-ad5b-5b121c7c797c
		summarizeBy: sum
		sourceColumn: NR_VOTAVEL

		annotation SummarizationSetBy = Automatic

	column NM_VOTAVEL
		dataType: string
		lineageTag: d9f521f6-3239-46fa-a6b7-d4fe25d358e9
		summarizeBy: none
		sourceColumn: NM_VOTAVEL

		annotation SummarizationSetBy = Automatic

	column QT_VOTOS
		dataType: int64
		formatString: 0
		lineageTag: 4e14d4c6-2d2e-42cf-8a41-dec1e5829fbf
		summarizeBy: sum
		sourceColumn: QT_VOTOS

		annotation SummarizationSetBy = Automatic

	column NR_TURNO
		dataType: int64
		formatString: 0
		lineageTag: 1c182614-307d-4990-b1e0-22454c08ee5f
		summarizeBy: sum
		sourceColumn: NR_TURNO

		annotation SummarizationSetBy = Automatic

	column CD_TIPO_ELEICAO
		dataType: int64
		lineageTag: d8836c3a-2fe7-4069-addc-0bc0fa68ce80
		summarizeBy: sum
		sourceColumn: CD_TIPO_ELEICAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAND_KEY
		dataType: string
		lineageTag: 3587d757-3122-4160-b3cb-713c2ac1e724
		summarizeBy: none
		sourceColumn: CAND_KEY

		annotation SummarizationSetBy = Automatic

	column CD_CARGO
		dataType: int64
		formatString: 0
		lineageTag: 6c7e9686-a88f-4f38-8fdb-210025fa42b8
		summarizeBy: sum
		sourceColumn: CD_CARGO

		annotation SummarizationSetBy = Automatic

	column LOC_KEY
		dataType: string
		lineageTag: d8136937-ab82-4564-887b-9fbdb74cfd61
		summarizeBy: none
		sourceColumn: LOC_KEY

		annotation SummarizationSetBy = Automatic

	column COLOC_KEY
		dataType: string
		lineageTag: 5bc528a7-82c5-44ea-9217-1dc3618bb70c
		summarizeBy: none
		sourceColumn: COLOC_KEY

		annotation SummarizationSetBy = Automatic

	column COLOCACAO
		dataType: int64
		formatString: 0
		lineageTag: 9faebd1b-2be1-4fab-acfb-15c142c16aac
		summarizeBy: sum
		sourceColumn: COLOCACAO

		annotation SummarizationSetBy = Automatic

	column PARTIDO
		dataType: string
		lineageTag: 7c7cfd1a-70db-4959-bf8a-50c74c4af139
		summarizeBy: none
		sourceColumn: PARTIDO

		annotation SummarizationSetBy = Automatic

	column __index_level_0__
		dataType: int64
		formatString: 0
		lineageTag: 1739885d-3e0f-4f96-8096-5720324e86a7
		summarizeBy: sum
		sourceColumn: __index_level_0__

		annotation SummarizationSetBy = Automatic

	partition votacao_secao_2022_PE = m
		mode: import
		source = ```
				let
				    Source = Parquet.Document(File.Contents("C:\Users\Pedro\Desktop\CSV_Samples\CENSO_Eleicoes_2022_PE\Parquets\votacao_secao_2022_PE.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"NR_ZONA", Int64.Type}, {"NR_SECAO", Int64.Type}, {"DS_CARGO", type text}, {"NR_VOTAVEL", Int64.Type}, {"NM_VOTAVEL", type text}, {"QT_VOTOS", Int64.Type}, {"LOC_KEY", type text}}),
				    #"Add CAND_KEY" = Table.AddColumn(
				    #"Changed Type",
				    "CAND_KEY",
				    each 
				        Text.From([DS_CARGO]) & 
				        "-" & 
				        Text.From([NR_VOTAVEL]),
				    type text
				)
				in
				    #"Add CAND_KEY"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

