table customer
	lineageTag: bf9c0c2f-c7be-4beb-aab9-f702dba5acbd

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 1dd52253-6a28-418c-a247-1dbdb8d59cd6
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column GeoAreaKey
		dataType: int64
		formatString: 0
		lineageTag: a1a4ff0e-3d0e-4b29-be17-60c390b49082
		summarizeBy: none
		sourceColumn: GeoAreaKey

		annotation SummarizationSetBy = Automatic

	column StartDT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3e7dec1a-9be5-4732-9b60-6082750ea006
		summarizeBy: none
		sourceColumn: StartDT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 50922d91-4338-4950-ac04-e8c1b2ea9a04
		summarizeBy: none
		sourceColumn: EndDT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Continent
		dataType: string
		lineageTag: dc927dba-66bb-451f-bcc6-7405d4709b97
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: c740c0e5-542b-486f-a362-0a67fb68b8ea
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: ed9f5685-1745-4a8d-b9e9-870f8dd2198e
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column GivenName
		dataType: string
		lineageTag: b3d01ab0-659a-49f9-a5da-3d5082a00166
		summarizeBy: none
		sourceColumn: GivenName

		annotation SummarizationSetBy = Automatic

	column MiddleInitial
		dataType: string
		lineageTag: 912dbb20-a5cf-461e-b24d-8ce9504961f1
		summarizeBy: none
		sourceColumn: MiddleInitial

		annotation SummarizationSetBy = Automatic

	column Surname
		dataType: string
		lineageTag: 8e277294-9454-4802-a618-a8c3d5e467e7
		summarizeBy: none
		sourceColumn: Surname

		annotation SummarizationSetBy = Automatic

	column StreetAddress
		dataType: string
		lineageTag: 04a99cfe-265b-4f2b-944f-696f17311e5e
		summarizeBy: none
		sourceColumn: StreetAddress

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 8b4cec84-37a9-4fbd-a0ee-e4d9a2aaf9af
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 608ff3ff-830a-4551-b49d-483d3d68cdbd
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column StateFull
		dataType: string
		lineageTag: 62883e12-e365-4b2d-b3b1-7a1ebbb26e61
		summarizeBy: none
		sourceColumn: StateFull

		annotation SummarizationSetBy = Automatic

	column ZipCode
		dataType: string
		lineageTag: 47ef00d6-7f43-4ddd-9567-4e536f2c6212
		summarizeBy: none
		sourceColumn: ZipCode

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 326ca2a0-dcc2-4277-9e02-f165c8ace54c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column CountryFull
		dataType: string
		lineageTag: 7bf32c45-5df2-45e6-99fb-18d3c69ed135
		summarizeBy: none
		sourceColumn: CountryFull

		annotation SummarizationSetBy = Automatic

	column Birthday
		dataType: dateTime
		formatString: Long Date
		lineageTag: 74cae1ae-d0f7-4bca-9418-89d332746747
		summarizeBy: none
		sourceColumn: Birthday

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 8ded197c-9f57-4c15-ad55-62675962837a
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 2b0bc347-5484-4473-9417-09c3560506e7
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 3b5a370f-95df-4b34-8512-6d5d6be1eb40
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Vehicle
		dataType: string
		lineageTag: 23155be8-ccf9-4c61-a503-d6e1d7a1c1eb
		summarizeBy: none
		sourceColumn: Vehicle

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: int64
		formatString: 0
		lineageTag: 62790648-5b79-477f-919f-0c1ef6adb425
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: int64
		formatString: 0
		lineageTag: 1ddb46b9-fc96-42c1-a83f-9f1edb688c63
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

	partition customer = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PathCsv & "\CSV_Samples\Contoso\customer.csv"),[Delimiter=",",
				 Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"GeoAreaKey", Int64.Type}, {"StartDT", type date}, {"EndDT", type date}, {"Continent", type text}, {"Gender", type text}, {"Title", type text}, {"GivenName", type text}, {"MiddleInitial", type text}, {"Surname", type text}, {"StreetAddress", type text}, {"City", type text}, {"State", type text}, {"StateFull", type text}, {"ZipCode", type text}, {"Country", type text}, {"CountryFull", type text}, {"Birthday", type date}, {"Age", Int64.Type}, {"Occupation", type text}, {"Company", type text}, {"Vehicle", type text}, {"Latitude", Int64.Type}, {"Longitude", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

