table store
	lineageTag: d63ea434-b4dc-4b6d-b800-e4293dba8979

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 71ad69cd-16ba-4510-bc1d-bd174f69037b
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column StoreCode
		dataType: int64
		formatString: 0
		lineageTag: 7e82654b-026c-4661-aed4-977f6fe6d494
		summarizeBy: none
		sourceColumn: StoreCode

		annotation SummarizationSetBy = Automatic

	column GeoAreaKey
		dataType: int64
		formatString: 0
		lineageTag: 81ba4aa0-f6bf-459c-8840-c58910528df5
		summarizeBy: none
		sourceColumn: GeoAreaKey

		annotation SummarizationSetBy = Automatic

	column CountryCode
		dataType: string
		lineageTag: b80ae9d9-3433-41cd-8b17-51ab01a48216
		summarizeBy: none
		sourceColumn: CountryCode

		annotation SummarizationSetBy = Automatic

	column CountryName
		dataType: string
		lineageTag: 1a70caef-06d3-4e16-8c5a-9885e105e53a
		summarizeBy: none
		sourceColumn: CountryName

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 093f1851-7e17-49b3-b1c0-5ddc2f71ea60
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1f7bdb68-3641-4d70-b626-82a7a734c478
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CloseDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45c2115b-d085-47ae-91c2-a6d1179443cd
		summarizeBy: none
		sourceColumn: CloseDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Description
		dataType: string
		lineageTag: 06a0ee83-e416-4ed1-83d3-595c028b2aea
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column SquareMeters
		dataType: int64
		formatString: 0
		lineageTag: 525f3dd8-f26e-49d0-83d8-5a797c759ad5
		summarizeBy: none
		sourceColumn: SquareMeters

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: a823dd2a-06ab-41fd-b780-af62f2a7df82
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition store = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PathCsv & "\CSV_Samples\Contoso\store.csv"),[Delimiter=",",
				 Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StoreKey", Int64.Type}, {"StoreCode", Int64.Type}, {"GeoAreaKey", Int64.Type}, {"CountryCode", type text}, {"CountryName", type text}, {"State", type text}, {"OpenDate", type date}, {"CloseDate", type date}, {"Description", type text}, {"SquareMeters", Int64.Type}, {"Status", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

